### ISSUE TITLE
Add Twitter Command for Trending Cryptocurrency

### ISSUE THREAD

**Issue by cleanunicorn** [cleanunicorn/nate#11]
## Description
Add a new CLI command to generate and post analytical tweets about trending cryptocurrencies. The command should fetch data from a crypto API (coinmarketcap/coingecko/..), analyze the trends, and create informative tweets about the most interesting coins.

## Features
- New CLI command: `twitter trending-crypto`
- Support for different trending categories:
  - Latest trending coins
  - Most visited coins
  - Top gainers
  - Top losers
- Generate neutral, analytical content focusing on top 3 coins in each category
- Include relevant metrics (price, % change, volume, etc.) depending on what the endpoint returns and what's relevant and interesting

### 1. Add New CLI Command
Add to `app/cli/commands.py`:
```python:app/cli/commands.py
@twitter.command(name="trending-crypto")
@click.option(
    "--category",
    "-c",
    type=click.Choice(['latest', 'visited', 'gainers', 'losers']),
    default='latest',
    help="Category of trending coins to analyze"
)
@click.option("--dry-run", "-d", is_flag=True, help="Generate tweet without posting")
def twitter_trending_crypto(category, dry_run):
    """Generate and post analytical tweets about trending cryptocurrencies"""
    pass
```

### 2. Create New Crypto Service
Create new file `app/services/CryptoService.py`:
- Implement API client for fetching crypto data
- Add methods for different trending categories
- Include data processing and analysis

### 3. Update Tweet Generator
Extend `TweetGeneratorOpenAI` to support crypto analysis:
- Add new prompt templates for crypto analysis
- Implement structured data formatting
- Ensure neutral, analytical tone

### 4. Sample Tweet Format
```
📊 Crypto Trend Analysis #crypto

Top 3 Gainers Today:
1. $BTC: +15.2% (24h)
   Volume: $45.2B | MC: $850B
2. $ETH: +12.1% (24h)
   Volume: $20.1B | MC: $350B
3. $SOL: +8.5% (24h)
   Volume: $5.2B | MC: $45B

Key Metrics & Analysis 🔍
#cryptocurrency #trading
```

## Tasks
1. [x] Create CryptoService class with API integration
2. [x] Add new CLI command implementation
3. [x] Update TweetGeneratorOpenAI for crypto content
4. [x] Add crypto-specific prompt templates
5. [x] Implement error handling for API failures
6. [x] Add unit tests for new functionality
7. [x] Update documentation

## Dependencies
- Crypto API service (e.g., CoinGecko, CoinMarketCap)
- Additional Python packages:
  - `requests` for API calls
  - `pandas` for data analysis

## Notes
- Ensure rate limiting compliance with chosen API
- Maintain neutral tone in analysis
- Include proper error handling for API downtime
- Add appropriate cryptocurrency hashtags
- Consider adding price alerts for significant movements

## Acceptance Criteria
- [x] Command successfully fetches and analyzes trending crypto data
- [x] Generates well-formatted, analytical tweets
- [x] Handles all trending categories correctly
- [x] Proper error handling and user feedback
- [x] Unit tests passing
- [x] Documentation updated
